# versão é obrigatório
version: '3' 
# lista de serviços a serem criados
services:
  # nome do primeiro 
  servidorweb: # posso mudar
    # nome da imagem que vai ser criada a partir do Dockerfile
    image: webservernginx # posso mudar
    # nome do meu container
    container_name: webserver # posso mudar
    # comando build que faz a criação
    build:
      context: .
    # comando que faz o redirecionamento de portas, portaseupc:portadocontainer  
    ports:
      - "8081:80" # posso mudar a porta do pc 
    #coloca meu container na rede  
    networks:
      #nome da rede
      - web_servereth # posso mudar

  #dados para crição do container do mysql
  mysql_db:
    image: "mysql:latest" #imagem vem do dockerhub, equivale ao from
    container_name: mysqlserver #nomeando container # posso mudar
    ports: # redirecionando as portas
      - "3307:3306" # primeira meu pc e seunda porta container
    environment: #variaveis de ambientes do mysql
      MYSQL_DATABASE: filmes # posso mudar
      MYSQL_USER: admin
      MYSQL_PASSWORD: r00tM)DT! # posso mudar
      MYSQL_ROOT_PASSWORD: r00tM)DT! # posso mudar
    volumes: #meu hd externo para o container
      - db_mysql:/var/lib/mysql
    networks: # uma rede entre os container
      - web_servereth # posso mudar
    ##fim do mysql

volumes:
  db_mysql:

#cria a rede
networks: 
  web_servereth: # posso mudar
    driver: bridge

    # comando para criar o container
    # docker-compose up -d
    # comando para excluir o container
    # docker-compose down
    # comando para startar o container
    # docker-compose start
    # comando para parar o container
    # docker-compose stop